export const accounts=[
   { email:'admin@admin.com',
    password:'123'},
    { email:'user@user.com',
    password:'123'}
]

export const itemList=[
    {
        content:'1',
        category:'c1',
        has:'admin@admin.com'
    },
    {
        content:'2',
        category:'c2',
        has:'admin@admin.com'
    },
    {
        content:'3',
        category:'c3',
        has:'admin@admin.com'
    },
    {
        content:'3',
        category:'c3',
        has:'admin@admin.com'
    },
    {
        content:'3',
        category:'c3',
        has:'admin@admin.com'
    },
    {
        content:'3',
        category:'c3',
        has:'admin@admin.com'
    },
    {
        content:'3',
        category:'c3',
        has:'admin@admin.com'
    },
    {
        content:'1',
        category:'c1',
        has:'admin@admin.com'
    },
    {
        content:'2',
        category:'c2',
        has:'user@user.com'
    },
    {
        content:'3',
        category:'c3',
        has:'user@user.com'
    },
    {
        content:'3',
        category:'c3',
        has:'user@user.com'
    },
    {
        content:'3',
        category:'c3',
        has:'user@user.com'
    },
    {
        content:'3',
        category:'c3',
        has:'user@user.com'
    },
]